services:
  backend:
    build:
      context: .  
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend-network
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
   
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend-network
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend-network
    volumes:
      - redis-data:/data
    command: >
      /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"

volumes:
  redis-data:
  mongo-data:
  mongo-config:

networks:
  backend-network:
