services:
  backend:
    build:
      context: .
      args:
        - NODE_ENV=test
    restart: always
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - ./.env.test
    environment:
      - REDIS_URL=redis://default@host.docker.internal:6379
      - REDIS_HOST=host.docker.internal
      - MONGO_URI=mongodb://mongo-user:mongo-password@host.docker.internal:27017
    depends_on:
      - test-mongo
      - test-redis
    command: >
      sh -c "npm run start:dev"

  test-mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./.env.test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  test-redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"